eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_DISCOVERY_ZONE}
    instance:
        instance-id: ${spring.application.name}:${instanceId:${random.value}}
server:
    port: 0
spring:
    application:
        name: ${SERVICE_NOTIFICATIONS_NAME}
    data:
        mongodb:
            host: ${SERVICE_NOTIFICATIONS_MONGO_HOST}
    kafka:
        consumer:
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
            group-id: notifications
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                spring:
                    json:
                        trusted:
                            packages: com.mateuszziomek.issuestracker.*
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        properties:
            mail:
                smtp:
                    auth: false
