eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_ZONE}
spring:
  application:
    name: ${SERVICE_NOTIFICATIONS_NAME}
  data:
    mongodb:
      host: ${SERVICE_NOTIFICATIONS_MONGO_HOST}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: false
