eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_ZONE}
spring:
  application:
    name: ${SERVICE_ORGANIZATIONS_COMMAND_NAME}
  data:
    mongodb:
      host: ${SERVICE_ORGANIZATIONS_COMMAND_MONGO_HOST}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
