eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_ZONE}
jwt:
  secret: ${JWT_SECRET}
spring:
  application:
    name: ${SERVICE_USERS_QUERY_NAME}
  data:
    mongodb:
      host: ${SERVICE_USERS_QUERY_MONGO_HOST}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
