eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_ZONE}
rest:
  client:
    notifications:
      name: ${SERVICE_NOTIFICATIONS_NAME}
spring:
  application:
    name: ${SERVICE_ISSUES_QUERY_NAME}
  data:
    mongodb:
      host: ${SERVICE_ISSUES_QUERY_MONGO_HOST}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
