name: test-frontend
on: [push]
jobs:
  typescript:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/package.json
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install
      - name: Typescript check
        working-directory: ./frontend
        run: yarn run lint:check
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/package.json
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install
      - name: Lint check
        working-directory: ./frontend
        run: yarn run lint:check
