name: test-backend
on:
  - push
  - pull_request
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Test
        working-directory: ./backend/issues-tracker
        run: ./mvnw -Dspring.profiles.active=test test
